export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_SUCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCHUSER_REQUEST = 'FETCHUSER_REQUEST';
export const FETCHUSER_PENDING = 'FETCHUSER_PENDING';
export const FETCHUSER_SUCCESS = 'FETCHUSER_SUCCESS';
export const FETCHUSER_FAIL = 'FETCHUSER_FAIL';

export const FETCH_ACTIVE_MESSAGE_REQUEST = 'FETCH_ACTIVE_MESSAGE_REQUEST';
export const STOP_FETCH_ACTIVE_MESSAGE_REQUEST = 'STOP_FETCH_ACTIVE_MESSAGE_REQUEST';
export const FETCH_ACTIVE_MESSAGE_SUCCESS = 'FETCH_ACTIVE_MESSAGE_SUCCESS';
export const FETCH_ACTIVE_MESSAGE_FAIL = 'FETCH_ACTIVE_MESSAGE_FAIL';
export const ACTIVE_MESSAGE_ADDED = 'ACTIVE_MESSAGE_ADDED';
export const ACTIVE_MESSAGE_CHANGED = 'ACTIVE_MESSAGE_CHANGED';
export const ACTIVE_MESSAGE_REMOVE = 'ACTIVE_MESSAGE_CHANGED';
