export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_PENDING = 'LOGIN_PENDING';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST';
export const LOGOUT_SUCCESS = 'LOGOUT SUCCESS';
export const LOGOUT_FAIL = 'LOGOUT_FAIL';

export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_PENDING = 'REGISTER_PENDING';
export const REGISTER_SUCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const FETCHUSER_REQUEST = 'FETCHUSER_REQUEST';
export const FETCHUSER_PENDING = 'FETCHUSER_PENDING';
export const FETCHUSER_SUCCESS = 'FETCHUSER_SUCCESS';
export const FETCHUSER_FAIL = 'FETCHUSER_FAIL';

export const FETCH_ACTIVE_MESSAGE_REQUEST = 'FETCH_ACTIVE_MESSAGE_REQUEST';
export const STOP_FETCH_ACTIVE_MESSAGE_REQUEST = 'STOP_FETCH_ACTIVE_MESSAGE_REQUEST';
export const ACTIVE_MESSAGE_ADDED = 'ACTIVE_MESSAGE_ADDED';
export const ACTIVE_MESSAGE_CHANGED = 'ACTIVE_MESSAGE_CHANGED';
export const ACTIVE_MESSAGE_REMOVED = 'ACTIVE_MESSAGE_REMOVED';

export const FETCH_CHAT_REQUEST = 'FETCH_CHAT_REQUEST';
export const STOP_FETCH_CHAT_REQUEST = 'STOP_FETCH_CHAT_REQUEST';
export const CHAT_REQUEST_ADDED = 'CHAT_REQUEST_ADDED';
export const CHAT_REQUEST_CHANGED = 'CHAT_REQUEST_CHANGED';
export const CHAT_REQUEST_REMOVED = 'CHAT_REQUEST_REMOVED';

export const INIT_CHAT_THREAD_REQUEST = 'INIT_CHAT_THREAD_REQUEST';
export const INIT_CHAT_THREAD_SUCCESS = 'INIT_CHAT_THREAD_COMPLETE';
export const INIT_CHAT_THREAD_FAIL = 'INIT_CHAT_THREAD_FAIL';

export const FETCH_CHAT_MESSAGE_REQUEST = 'FETCH_CHAT_MESSAGE_REQUEST';
export const STOP_FETCH_CHAT_MESSAGE_REQUEST = 'STOP_FETCH_CHAT_MESSAGE_REQUEST';
export const CHAT_MESSAGE_ADDED = 'CHAT_MESSAGE_ADDED';
export const CHAT_MESSAGE_CHANGED = 'CHAT_MESSAGE_CHANGED';
export const CHAT_MESSAGE_REMOVED = 'CHAT_MESSAGE_REMOVED';
export const CHECK_SEEN_MESSAGE_REQUEST = 'SEEN_MESSAGE_REQUEST';
export const CHECK_SEEN_MESSAGE_SUCCESS = 'CHECK_SEEN_MESSAGE_SUCCESS';
export const SEND_MESSAGE_REQUEST = 'SEND_MESSAGE_REQUEST';
export const SEND_MESSAGE_SUCCESS = 'SEND_MESSAGE_SUCCESS';
export const SEND_MESSAGE_FAIL = 'SEND_MESSAGE_FAIL';
